# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='questionnaire',
            new_name='building',
        ),
    ]
