# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20161101_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='option_count',
            field=models.IntegerField(default=0),
        ),
    ]
