# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_building_option_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_after_ddl',
            field=models.BooleanField(default=False),
        ),
    ]
