# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_building_is_after_ddl'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
