# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_option_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
