# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_option_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydetail',
            name='theme',
            field=models.CharField(default='该字段用以区分不同activity，不显示', max_length=100),
        ),
    ]
